# Generated by Django 5.0.14 on 2026-07-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_gst_asset_invoice_date_asset_invoice_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
